### ISSUE TITLE
Multiple devices identified as 00000000-0000-4000-8000-000000000000

### ISSUE THREAD

**Issue by talski** [jonghoon023/unique_device_identifier#1]
Almost half of chrome devices are being identified as same 00000000-0000-4000-8000-000000000000

**Comment by jonghoon023** [comment]
Thank you for opening this issue. I will begin looking into the problem shortly.

**Comment by jonghoon023** [comment]
@talski 

Hi, I've addressed the issue you reported.
Before proceeding with the deployment, I would greatly appreciate it if you could confirm that the problem has been fully resolved on your side.

Please follow the steps below:
1. Update your pubspec.yaml as follows:
```yaml
unique_device_identifier:
  git: https://github.com/jonghoon023/unique_device_identifier.git
  ref: fix/1
```

2. Run the following command in your terminal:
```bash
flutter build web --release --wasm
```

3. After running the build, please let me know the result.

I look forward to your feedback. Thank you.
